version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-example
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-proxy:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: redis-proxy-example
    ports:
      - "8080:8080"
    environment:
      - REDIS_URLS=redis://redis:6379
      - SERVER_PORT=8080
      - AUTH_ENABLED=true
      - JWT_SECRET=example-secret-key-change-in-production
      - API_KEYS=example-api-key-123,another-key-456
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_REQUESTS=1000
      - RATE_LIMIT_WINDOW=60
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: